FROM kalilinux/kali-rolling:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    nmap dnsutils whois whatweb \
    httpx-toolkit gobuster \
    nuclei sqlmap \
    curl wget ffuf \
    git jq \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN nuclei -update-templates

WORKDIR /workspace
ENTRYPOINT ["/bin/bash", "-c"]
